CLS
FOR I = 1 TO 10
10 A = INT(RND(1) * 100)
B = INT(RND * 100)
30 PRINT A; "+"; B; "=";
INPUT C
IF C = A + B THEN PRINT "V": D = D + 10: GOTO 70
PRINT "X"
70 NEXT I
PRINT "FEN"; D,
IF D > 89 THEN PRINT "YOU"
IF D > 79 AND D < 90 THEN PRINT "LIANG"
IF D > 59 AND D < 70 THEN PRINT "JIGE"
IF D < 60 THEN PRINT "BUJIGE"
END

